

ATFW_OPT_icorerz2ge = "LSI=G2E RCAR_SA0_SIZE=0 RCAR_AVS_SETTING_ENABLE=0 RZG_EK874=1 PMIC_ROHM_BD9571=0 RCAR_SYSTEM_SUSPEND=0 RCAR_DRAM_DDR3L_MEMCONF=0 RCAR_DRAM_DDR3L_MEMDUAL=0 SPD="none""

COMPATIBLE_MACHINE = "(ek874|hihope-rzg2m|hihope-rzg2n|icorerz2ge)"

